### ISSUE TITLE
Art License

### ISSUE THREAD

**Issue by clienthax** [DePhoegon/chococraft-delbase_patch#1]
Hi,

As per the license of https://github.com/Mrbysco/ChocoCraft4
Art included in chococraft 4 is not under the MIT license but is [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/),
https://github.com/Mrbysco/ChocoCraft4/blob/1.18.x/LICENSE-art.md

As you make use of these assets you are required to maintain the existing license.

**Comment by Sunconure11** [comment]
@clienthax Yeah it is clear this guy is ignoring you.

@DePhoegon

**Comment by DePhoegon** [comment]
> @clienthax Yeah it is clear this guy is ignoring you.
> 
> @DePhoegon

Ya, because Totally missing the one damn'd Text file, I totally am just claiming I did it all.

You people are just the bloody worst ...  Quite seriously.  The most meaningless and worthless hangnail of a file that could have been lost in the absurd back and forth.

Oh, you can redo all the art to visually tell them apart, and literally overlook a non functional file.   Though by the way, The use of the model in the code it self could bypass any 'art' from forked mod upfront.   (block bench) and and it spits out a model...

But if the the two text based md files that got overlooked will sate you're minds at ease.

This is also to point out that I'd owed more in digital art assets to MC/MOJANG directly for block pallets, but .. Oh no  Block benched models of Chocobos, using the same coded blocks in sequence share similar colors, one must be copying each other...... never mind the differences in actual color, behavior, spawning, breeding, or ability/use.    

This is the feedback I get.. 'Licence the work correctly', not about the fing hidden bug within my base mode that used by this...  I get 'herp ta derp, you're a copy'   
-not a word on how changes and paths were taken that exceptionally different from the forked mod, even more so with of where it where was would be suggesting that it went from broken to ... working alone (from the borked 1.18.1 version) on my own, before the developer picked it back up & started working on it again.       I get this static, because herp ta derp ....  I must done no work what so ever.

w/e, I'm putting those .. dumpta ta dah... files that will only exist in the source code, because people like you have spiked thors currently in use & can't find pleasure without being a twat... 

Also, 'clientHax'  I want to point out that I know who you are, & the fact that you would just scream thief on curseforge, for 'art assets' that don't even show the credits on curseforge, on curseforge..   says alot about your insanity.  Seriously though,  You picked the dumbest shit to have your panties in a twisted about.  It could have been.  'Oh did you know you forgot the license-art file? Could you include it'  Because, Bumpity bumpity Bumpity... that would have been more helpful than breaking Curseforge TOS & calling me a thief, instead of someone who cloned a MIT project for my own & friend use (or those who'd like to see how I'd take it), and forgetting two text based md files despite the commented annotations of the work credit being inside the code as well.

I really hope chococraft does well, but you need your ego checked you child.
---------------------
I'd honestly had killed for actual bug reports/advice, but  I got what I got.   (added the stupid files because it's just easier, and frankly I want people to enjoy the game as they'd like)
